# Generated by Django 4.1.2 on 2023-01-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="times",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
