# Generated by Django 4.1.2 on 2023-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_alter_records_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="times",
            field=models.IntegerField(),
        ),
    ]
