# Generated by Django 4.1.2 on 2023-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_records_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="kings",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
