# Generated by Django 4.1.2 on 2023-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_alter_records_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="kings",
            field=models.CharField(max_length=100),
        ),
    ]
